baseURL = 'https://danielmillward.com/'
languageCode = 'en-us'
title = 'Daniel Millward'
theme = "dmCustomTheme"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    url = "/posts"
  [[menu.main]]
    name = "Tags"
    url = "/tags"